### ISSUE TITLE
Rename repository to RiffRaff

### ISSUE THREAD

**Issue by philwills** [guardian/riff-raff#255]
People often fail to find this repository because it's commonly referred to as RiffRaff. I'd also like to change the build name, but we can probably do that as part of moving the build out of TeamCity.

cc @jennysivapalan @Reettaphant @sihil

**Comment by philwills** [comment]
Also should it then be `riff-raff`? That seems most consistent with naming elsewhere to me.

**Comment by jennysivapalan** [comment]
Agreed `riff-raff` to be consistent.

**Comment by sihil** [comment]
I've done this. To `riffraff` initially (since that was the sub domain), but am happy with the consensus I found here. GitHub seems to automatically redirect which is nice and I've updated TeamCity.

You'll need to reclone or update the origin on your existing repos: `git remote set-url origin git@github.com:guardian/riff-raff.git`.
